services:
#    camille_blog.example:
#        class: Camille\BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    camille_blog.antispam:
        class: Camille\BlogBundle\Antispam\CamilleAntispam
        arguments: [@mailer, %locale%, 50] # tableau d'arguments