<?php

namespace Camille\BlogBundle\Entity;

/**
 * ThumbnailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThumbnailRepository extends \Doctrine\ORM\EntityRepository
{
}
